name: MERN CI/CD with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
     
      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build
      
      - name: Build Docker image for client
        run: docker build -t hibab/mern-client:latest ./client

      - name: Build Docker image for server
        run: docker build -t hibab/mern-server:latest ./server

      - name: Test backend
        run: npm test
        working-directory: ./server

      - name: Start server
        run: npm start 
        working-directory: ./server

      - name: Wait for server to start
        run: sleep 5s

      - name: Run frontend tests
        run: npm test
        working-directory: ./client

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Push Docker images to Docker Hub
        run: |
          docker push hibab/mern-client:latest
          docker push hibab/mern-server:latest
