name: MERN CI/CD with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t your-docker-image-name .
        working-directory: ./client

      - name: Test backend
        run: npm test
        working-directory: ./server

      - name: Start server
        run: npm start 
        working-directory: ./server

      - name: Wait for server to start
        run: sleep 5s

      - name: Run frontend tests
        run: npm test
        working-directory: ./client
           
      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Push Docker image to Docker Hub
        run: docker push hibab/MERN:latest

 
